# Generated by Django 4.2.1 on 2023-05-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Disel', 'Disel')], default='Gasolina', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'Combustivel',
                'ordering': [],
            },
        ),
    ]
