# Generated by Django 4.2.1 on 2023-05-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combustivel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combustivel',
            options={'ordering': [], 'verbose_name': 'Combustível', 'verbose_name_plural': 'Combustíveis'},
        ),
    ]
