# Generated by Django 4.2.1 on 2023-05-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combustivel', '0002_alter_combustivel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combustivel',
            name='valor',
        ),
    ]
