# Generated by Django 4.2.1 on 2023-05-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustivel', '0003_remove_combustivel_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustivel',
            name='tipo_de_combustivel',
            field=models.CharField(choices=[(1, 'Gasolina'), (2, 'Gasolina Aditivada'), (3, 'Disel'), (4, 'Disel Aditivado')], default=None, max_length=20),
        ),
    ]
