# Generated by Django 4.2.1 on 2023-05-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustivel', '0004_alter_combustivel_tipo_de_combustivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combustivel',
            options={'verbose_name': 'Combustível', 'verbose_name_plural': 'Combustíveis'},
        ),
        migrations.AlterField(
            model_name='combustivel',
            name='tipo_de_combustivel',
            field=models.IntegerField(choices=[(1, 'Gasolina'), (2, 'Gasolina Aditivada'), (3, 'Disel'), (4, 'Disel Aditivado')], default=1),
        ),
    ]
