# Generated by Django 4.2.1 on 2023-05-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bomba_de_combustivel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomba',
            old_name='numero_bomba',
            new_name='numero',
        ),
    ]
