# Generated by Django 4.2.1 on 2023-05-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0002_alter_posto_options'),
        ('bomba_de_combustivel', '0002_rename_numero_bomba_bomba_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomba',
            options={'verbose_name': 'Bomba de Combustível', 'verbose_name_plural': 'Bombas de Combustível'},
        ),
        migrations.AddField(
            model_name='bomba',
            name='posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posto.posto', verbose_name='Posto'),
        ),
    ]
