# Generated by Django 4.2.1 on 2023-05-25 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=100, verbose_name='CPF')),
                ('contato', models.CharField(max_length=100, verbose_name='Contato')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereço')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcao.funcao', verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'db_table': 'Colaborador',
                'ordering': [],
            },
        ),
    ]
