# Generated by Django 4.2.1 on 2023-05-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0003_alter_posto_options'),
        ('usuario', '0002_alter_usuario_posto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='posto',
            field=models.ManyToManyField(related_name='usuario', to='posto.posto', verbose_name='Posto'),
        ),
    ]
