# Generated by Django 4.2.1 on 2023-05-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vigencia_de_preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustivel', models.CharField(max_length=100, verbose_name='Combustivel')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_de_vigencia', models.DateField(verbose_name='Data de Vigência')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Vigência de preço',
                'verbose_name_plural': 'Vigência de preços',
                'db_table': 'Vigencia_de_preco',
                'ordering': [],
            },
        ),
    ]
