# Generated by Django 4.2.1 on 2023-05-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virgencia_de_preco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vigencia_de_preco',
            name='status',
        ),
        migrations.AddField(
            model_name='vigencia_de_preco',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
