# Generated by Django 4.2.1 on 2023-05-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virgencia_de_preco', '0002_remove_vigencia_de_preco_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vigencia_de_preco',
            new_name='VigenciaDePreco',
        ),
    ]
