# Generated by Django 4.2.1 on 2023-05-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virgencia_de_preco', '0007_alter_vigenciadepreco_combustivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vigenciadepreco',
            name='data_de_vigencia',
        ),
        migrations.AddField(
            model_name='vigenciadepreco',
            name='data_de_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='vigenciadepreco',
            name='data_de_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
    ]
