# Generated by Django 4.2.1 on 2023-05-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'Posto',
                'ordering': [],
            },
        ),
    ]
