# Generated by Django 4.2.1 on 2023-05-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0002_alter_posto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posto',
            options={'verbose_name': 'Posto de Combustível', 'verbose_name_plural': 'Postos de Combustível'},
        ),
    ]
