# Generated by Django 4.2.1 on 2023-05-25 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=500, verbose_name='Código')),
                ('descricao', models.CharField(max_length=600, verbose_name='Descrição')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posto.posto', verbose_name='Posto')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'db_table': 'Função',
                'ordering': [],
            },
        ),
    ]
