# Generated by Django 4.2.1 on 2023-05-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcao',
            options={'verbose_name': 'Função', 'verbose_name_plural': 'Funções'},
        ),
    ]
