# Generated by Django 4.2.1 on 2023-05-25 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combustivel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combustivel.combustivel')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'Tanque',
                'ordering': [],
            },
        ),
    ]
