# Generated by Django 4.2.1 on 2023-05-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0002_alter_posto_options'),
        ('tanque', '0002_alter_tanque_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tanque',
            options={'verbose_name': 'Tanque de Combustível', 'verbose_name_plural': 'Tanques de Combustível'},
        ),
        migrations.AddField(
            model_name='tanque',
            name='posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posto.posto', verbose_name='Posto'),
        ),
    ]
