# Generated by Django 4.2.1 on 2023-05-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Disel', 'Disel')], default='Gasolina', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.combustivel')),
            ],
        ),
        migrations.CreateModel(
            name='Bomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bomba', models.IntegerField(blank=True, null=True)),
                ('tanques', models.ManyToManyField(to='abastecimento.tanque')),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frentista', models.CharField(blank=True, max_length=100, null=True)),
                ('litros_abastecido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.DateTimeField(verbose_name='Data do abastecimento')),
                ('bomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.bomba')),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.combustivel')),
            ],
        ),
    ]
