# Generated by Django 4.2.1 on 2023-05-25 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bomba_de_combustivel', '0001_initial'),
        ('combustivel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.CharField(blank=True, max_length=100, null=True)),
                ('litros_abastecido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.DateTimeField(verbose_name='Data do abastecimento')),
                ('bomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomba_de_combustivel.bomba')),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combustivel.combustivel')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'db_table': 'Abastecimento',
                'ordering': [],
            },
        ),
    ]
