# Generated by Django 4.2.1 on 2023-05-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combustivel', '0004_alter_combustivel_tipo_de_combustivel'),
        ('abastecimento', '0003_alter_abastecimento_combustivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abastecimento',
            name='valor_total',
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='combustivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combustivel.combustivel'),
        ),
    ]
