# Generated by Django 4.2.1 on 2023-05-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0002_alter_posto_options'),
        ('abastecimento', '0004_remove_abastecimento_valor_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abastecimento',
            options={'verbose_name': 'Abastecimento', 'verbose_name_plural': 'Abastecimentos'},
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='posto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posto.posto', verbose_name='Posto'),
        ),
    ]
