# Generated by Django 4.2.1 on 2023-06-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0005_alter_abastecimento_options_abastecimento_posto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do abastecimento'),
        ),
    ]
